"""refactored the rating models

Revision ID: 9f948e75af10
Revises: ef6e41deeadf
Create Date: 2024-04-16 00:56:27.040149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f948e75af10'
down_revision = 'ef6e41deeadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_value', sa.Integer(), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=True))
        batch_op.drop_column('rating_value')

    # ### end Alembic commands ###
